import { AnalysisJob } from '../types/analysis';
import axios from 'axios';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const API_URL = '/api';

export const historyApi = {
  getHistory: async (limit: number = 10): Promise<Array<{
    jobId: string;
    repoUrl: string;
    rubricId: string;
    status: string;
    progress: number;
    totalScore?: number;
    maxScore?: number;
    createdAt: string;
    updatedAt: string;
  }>> => {
    const response = await axios.get(`${API_URL}/analyze/history?limit=${limit}`);
    return response.data.jobs;
  },
};

export const exportPdf = (job: AnalysisJob): void => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Analysis Report', 14, 20);
  
  // Repository info
  doc.setFontSize(12);
  doc.text(`Repository: ${job.repoUrl}`, 14, 35);
  doc.text(`Date: ${new Date(job.createdAt).toLocaleString()}`, 14, 42);
  doc.text(`Status: ${job.status.toUpperCase()}`, 14, 49);
  
  if (job.result) {
    // Score
    doc.setFontSize(16);
    doc.setTextColor(37, 99, 235); // Blue
    doc.text(`Score: ${job.result.totalScore} / ${job.result.maxScore}`, 14, 65);
    doc.setTextColor(0, 0, 0); // Reset to black
    
    // Global comment
    doc.setFontSize(11);
    const splitComment = doc.splitTextToSize(job.result.globalComment, 180);
    doc.text(splitComment, 14, 75);
    
    // Criteria table
    const tableData = job.result.criteria.map(c => [
      c.name,
      c.status.toUpperCase(),
      `${c.score}/${c.maxPoints}`,
      c.justification.substring(0, 60) + (c.justification.length > 60 ? '...' : ''),
    ]);
    
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (doc as any).autoTable({
      startY: 90,
      head: [['Criterion', 'Status', 'Score', 'Justification']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 10 },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 25 },
        2: { cellWidth: 25 },
        3: { cellWidth: 'auto' },
      },
    });
  }
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated by EpiGrader - Page ${i} of ${pageCount}`, 14, 285);
  }
  
  // Save
  doc.save(`analysis-${job.id}.pdf`);
};

// Keep markdown export as fallback
export const exportMarkdown = (job: AnalysisJob): void => {
  const content = generateReportContent(job);
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `analysis-${job.id}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const generateReportContent = (job: AnalysisJob): string => {
  const lines = [
    `# Analysis Report`,
    ``,
    `**Repository:** ${job.repoUrl}`,
    `**Date:** ${new Date(job.createdAt).toLocaleString()}`,
    `**Status:** ${job.status}`,
    ``,
  ];

  if (job.result) {
    lines.push(`## Score: ${job.result.totalScore} / ${job.result.maxScore}`, ``);
    lines.push(`### Global Comment`, job.result.globalComment, ``);
    lines.push(`### Criteria`, ``);

    job.result.criteria.forEach(c => {
      lines.push(`#### ${c.name} (${c.score}/${c.maxPoints})`);
      lines.push(`Status: ${c.status}`);
      lines.push(`Justification: ${c.justification}`, ``);
    });
  }

  return lines.join('\n');
};