import { useHistory } from '../hooks/useHistory';
import { useNotification } from '../contexts/NotificationContext';
import { analysisApi } from '../services/analysis';
import { AnalysisJob, AnalyzedCriterion } from '../types/analysis';
import { useState } from 'react';
import { 
  History, Download, RefreshCw, Loader2, ExternalLink, Clock, 
  CheckCircle, XCircle, Sparkles, FileText, ChevronRight, 
  AlertCircle, FileDown
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const HistoryPage = () => {
  const { history, isLoading, error, refresh } = useHistory();
  const { success, error: showError } = useNotification();
  const [selectedJob, setSelectedJob] = useState<string | null>(null);
  const [jobDetails, setJobDetails] = useState<AnalysisJob | null>(null);
  const [loadingDetails, setLoadingDetails] = useState(false);

  const handleViewDetails = async (jobId: string) => {
    setLoadingDetails(true);
    setSelectedJob(jobId);
    try {
      const details = await analysisApi.getJobStatus(jobId);
      setJobDetails(details);
    } catch (err) {
      showError('Failed to load job details');
    } finally {
      setLoadingDetails(false);
    }
  };

  const handleExportPDF = (job: AnalysisJob) => {
    if (!job.result) {
      showError('No results to export');
      return;
    }

    const doc = new jsPDF();
    const repoName = job.repoUrl.split('/').pop() || 'repository';
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(30, 58, 95);
    doc.text('EpiGrader Analysis Report', 14, 20);
    
    // Repository info
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Repository: ${job.repoUrl}`, 14, 35);
    doc.text(`Date: ${new Date(job.createdAt).toLocaleString('fr-FR')}`, 14, 42);
    doc.text(`Status: ${job.status}`, 14, 49);
    
    // Score
    doc.setFontSize(16);
    doc.setTextColor(30, 58, 95);
    doc.text(`Score: ${job.result.totalScore} / ${job.result.maxScore}`, 14, 65);
    
    // Global comment
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const splitComment = doc.splitTextToSize(job.result.globalComment, 180);
    doc.text(splitComment, 14, 75);
    
    // Criteria table
    const tableData = job.result.criteria.map((c: AnalyzedCriterion) => [
      c.name,
      c.description.substring(0, 50) + (c.description.length > 50 ? '...' : ''),
      `${c.score}/${c.maxPoints}`,
      c.status === 'passed' ? '✓' : c.status === 'failed' ? '✗' : '~',
    ]);
    
    autoTable(doc, {
      startY: 90,
      head: [['Criterion', 'Description', 'Score', 'Status']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [30, 58, 95] },
      styles: { fontSize: 10 },
    });
    
    // Justifications
    let yPos = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.setTextColor(30, 58, 95);
    doc.text('Detailed Justifications:', 14, yPos);
    yPos += 10;
    
    job.result.criteria.forEach((c: AnalyzedCriterion, index: number) => {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(10);
      doc.setTextColor(30, 58, 95);
      doc.text(`${index + 1}. ${c.name} (${c.score}/${c.maxPoints})`, 14, yPos);
      yPos += 6;
      
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const splitJustification = doc.splitTextToSize(c.justification, 180);
      doc.text(splitJustification, 14, yPos);
      yPos += splitJustification.length * 5 + 8;
    });
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by EpiGrader - Page ${i}/${pageCount}`, 14, 290);
    }
    
    doc.save(`epigrader-report-${repoName}-${Date.now()}.pdf`);
    success('PDF exported successfully!');
  };

  const handleExportJSON = (job: AnalysisJob) => {
    if (!job.result) {
      showError('No results to export');
      return;
    }

    const report = {
      repository: job.repoUrl,
      date: job.createdAt,
      status: job.status,
      totalScore: job.result.totalScore,
      maxScore: job.result.maxScore,
      globalComment: job.result.globalComment,
      criteria: job.result.criteria,
    };
    
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `epigrader-report-${job.repoUrl.split('/').pop()}-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    success('JSON exported successfully!');
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed':
        return 'text-emerald-600 bg-emerald-100';
      case 'error':
        return 'text-red-600 bg-red-100';
      case 'processing':
        return 'text-blue-600 bg-blue-100';
      default:
        return 'text-gray-600 bg-gray-100';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return CheckCircle;
      case 'error':
        return XCircle;
      case 'processing':
        return Clock;
      default:
        return Clock;
    }
  };

  const formatRepoUrl = (url: string) => {
    const match = url.match(/github\.com\/([^/]+\/[^/]+)/);
    return match ? match[1] : url;
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero */}
      <div className="bg-gradient-to-r from-[#1e3a5f] to-[#2d5a87] text-white py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <History className="w-8 h-8 text-[#ff6b35]" />
              <div>
                <h1 className="text-3xl font-bold">Analysis History</h1>
                <p className="text-white/80">View past analyses and export reports</p>
              </div>
            </div>
            <button
              onClick={refresh}
              disabled={isLoading}
              className="flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 rounded-xl transition-colors disabled:opacity-50"
            >
              {isLoading ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <RefreshCw className="w-5 h-5" />
              )}
              Refresh
            </button>
          </div>
        </div>
      </div>

      <main className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl mb-6 flex items-center gap-2">
            <XCircle className="w-5 h-5 flex-shrink-0" />
            {error}
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* History List */}
          <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
            <div className="p-6 border-b border-gray-100">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-[#1e3a5f]/10 rounded-lg">
                  <FileText className="w-5 h-5 text-[#1e3a5f]" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Recent Analyses</h2>
              </div>
            </div>

            <div className="max-h-[600px] overflow-y-auto">
              {history.length === 0 ? (
                <div className="text-gray-400 text-center py-12">
                  <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>No analyses yet</p>
                  <p className="text-sm mt-1">Go to Analyze to start one</p>
                </div>
              ) : (
                <div className="divide-y divide-gray-100">
                  {history.map((job) => {
                    const StatusIcon = getStatusIcon(job.status);
                    return (
                      <div
                        key={job.jobId}
                        onClick={() => handleViewDetails(job.jobId)}
                        className={`p-4 cursor-pointer transition-colors ${
                          selectedJob === job.jobId
                            ? 'bg-[#1e3a5f]/5 border-l-4 border-[#1e3a5f]'
                            : 'hover:bg-gray-50'
                        }`}
                      >
                        <div className="flex justify-between items-start">
                          <div className="flex items-center gap-3">
                            <StatusIcon className={`w-5 h-5 ${
                              job.status === 'completed' ? 'text-emerald-500' :
                              job.status === 'error' ? 'text-red-500' :
                              'text-blue-500'
                            }`} />
                            <div>
                              <p className="font-medium text-[#1e3a5f]">
                                {formatRepoUrl(job.repoUrl)}
                              </p>
                              <p className="text-sm text-gray-500">
                                {new Date(job.createdAt).toLocaleString('fr-FR')}
                              </p>
                            </div>
                          </div>
                          <span
                            className={`px-2.5 py-1 rounded-full text-xs font-medium ${getStatusColor(
                              job.status
                            )}`}
                          >
                            {job.status}
                          </span>
                        </div>
                        {job.totalScore !== undefined && (
                          <div className="mt-2 ml-8 text-sm">
                            <span className="text-gray-500">Score:</span>{' '}
                            <span className="font-semibold text-gray-900">
                              {job.totalScore} / {job.maxScore}
                            </span>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>

          {/* Details Panel - Full Analysis View */}
          <div className="bg-white rounded-2xl shadow-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-emerald-100 rounded-lg">
                  <FileText className="w-5 h-5 text-emerald-600" />
                </div>
                <h2 className="text-lg font-semibold text-gray-900">Analysis Details</h2>
              </div>
              {jobDetails?.status === 'completed' && (
                <div className="flex gap-2">
                  <button
                    onClick={() => handleExportPDF(jobDetails)}
                    className="flex items-center gap-2 px-3 py-1.5 text-sm bg-red-100 hover:bg-red-200 text-red-700 rounded-lg transition-colors"
                  >
                    <FileDown className="w-4 h-4" />
                    PDF
                  </button>
                  <button
                    onClick={() => handleExportJSON(jobDetails)}
                    className="flex items-center gap-2 px-3 py-1.5 text-sm bg-blue-100 hover:bg-blue-200 text-blue-700 rounded-lg transition-colors"
                  >
                    <Download className="w-4 h-4" />
                    JSON
                  </button>
                </div>
              )}
            </div>

            {!selectedJob && (
              <div className="text-gray-400 text-center py-16 bg-gray-50 rounded-xl border-2 border-dashed border-gray-200">
                <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-50" />
                <p>Select an analysis to view details</p>
              </div>
            )}

            {loadingDetails && (
              <div className="flex justify-center py-16">
                <Loader2 className="w-8 h-8 animate-spin text-[#1e3a5f]" />
              </div>
            )}

            {jobDetails && !loadingDetails && (
              <div className="space-y-6">
                {/* Status & Score */}
                <div className="flex justify-between items-center p-4 bg-gradient-to-r from-emerald-50 to-emerald-100 rounded-xl">
                  <div>
                    <span className="text-sm text-emerald-700">Total Score</span>
                    <div className="text-3xl font-bold text-emerald-600">
                      {jobDetails.result?.totalScore ?? '-'} 
                      <span className="text-lg text-emerald-400">/</span> 
                      {jobDetails.result?.maxScore ?? '-'}
                    </div>
                  </div>
                  <span
                    className={`px-4 py-2 rounded-full text-sm font-medium ${getStatusColor(
                      jobDetails.status
                    )}`}
                  >
                    {jobDetails.status}
                  </span>
                </div>

                {/* Repository Link */}
                <a
                  href={jobDetails.repoUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 p-3 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors"
                >
                  <ExternalLink className="w-5 h-5 text-gray-500" />
                  <span className="text-gray-700 truncate">{jobDetails.repoUrl}</span>
                  <ChevronRight className="w-4 h-4 text-gray-400 ml-auto" />
                </a>

                {/* Global Comment */}
                {jobDetails.result?.globalComment && (
                  <div className="p-4 bg-blue-50 rounded-xl border border-blue-100">
                    <h3 className="font-medium text-blue-900 mb-2">Overall Feedback</h3>
                    <p className="text-blue-800">{jobDetails.result.globalComment}</p>
                  </div>
                )}

                {/* Criteria Details */}
                {jobDetails.result?.criteria && (
                  <div>
                    <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
                      <CheckCircle className="w-5 h-5 text-emerald-500" />
                      Detailed Criteria Analysis
                    </h3>
                    <div className="space-y-4 max-h-[400px] overflow-y-auto">
                      {jobDetails.result.criteria.map((criterion: AnalyzedCriterion) => (
                        <div
                          key={criterion.id}
                          className="border border-gray-200 rounded-xl p-4 hover:shadow-md transition-shadow"
                        >
                          {/* Criterion Header */}
                          <div className="flex justify-between items-start mb-3">
                            <div className="flex items-center gap-3">
                              {criterion.status === 'passed' ? (
                                <CheckCircle className="w-6 h-6 text-emerald-500" />
                              ) : criterion.status === 'failed' ? (
                                <XCircle className="w-6 h-6 text-red-500" />
                              ) : (
                                <AlertCircle className="w-6 h-6 text-amber-500" />
                              )}
                              <div>
                                <h4 className="font-semibold text-gray-900">{criterion.name}</h4>
                                <p className="text-sm text-gray-500">{criterion.description}</p>
                              </div>
                            </div>
                            <div className="text-right">
                              <span className={`text-lg font-bold ${
                                criterion.status === 'passed' ? 'text-emerald-600' :
                                criterion.status === 'failed' ? 'text-red-600' :
                                'text-amber-600'
                              }`}>
                                {criterion.score}
                              </span>
                              <span className="text-gray-400">/{criterion.maxPoints}</span>
                            </div>
                          </div>

                          {/* Justification */}
                          <div className="bg-gray-50 rounded-lg p-3 mt-3">
                            <p className="text-sm text-gray-700">
                              <span className="font-medium">Feedback:</span> {criterion.justification}
                            </p>
                          </div>

                          {/* Code References */}
                          {criterion.references && criterion.references.length > 0 && (
                            <div className="mt-3">
                              <p className="text-xs font-medium text-gray-500 mb-2">References:</p>
                              <div className="space-y-1">
                                {criterion.references.map((ref, idx) => (
                                  <div key={idx} className="text-xs text-gray-600 bg-gray-100 rounded px-2 py-1">
                                    {ref.file}
                                    {ref.lines && ` (lines ${ref.lines[0]}-${ref.lines[1]})`}
                                  </div>
                                ))}
                              </div>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Export Buttons (bottom) */}
                {jobDetails.status === 'completed' && jobDetails.result && (
                  <div className="flex gap-3 pt-4 border-t">
                    <button
                      onClick={() => handleExportPDF(jobDetails)}
                      className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-gradient-to-r from-red-500 to-red-600 text-white rounded-xl hover:shadow-lg transition-all"
                    >
                      <FileDown className="w-5 h-5" />
                      Export PDF Report
                    </button>
                    <button
                      onClick={() => handleExportJSON(jobDetails)}
                      className="flex items-center justify-center gap-2 px-4 py-3 bg-gray-100 text-gray-700 rounded-xl hover:bg-gray-200 transition-all"
                    >
                      <Download className="w-5 h-5" />
                      JSON
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};